### ISSUE TITLE
ページのURL構成を決める

### ISSUE THREAD

**Issue by mosa-architect-study** [mosa-architect-study/replace-kintai#108]
どのURLを叩くとどの画面が表示されるのか

**Comment by eatski** [comment]
- `/` : 有給一覧画面
- `/new` :  新規申請画面
- `/admin` : 管理者画面
- `/login` : ログイン画面

**Comment by eatski** [comment]
更新や削除の画面は個別のURLを持たない

**Comment by ymucm** [comment]
ログイン画面のURLって必要ないですかね？

**Comment by eatski** [comment]
@ymucm 
ログイン画面ってどうするみたいな話で落ち着いたんだっけ。。。汗

**Comment by ymucm** [comment]
@itskihaga 
一応ログインボタンだけあるページを作ろっかってなってた気はします、多分笑
すがさんが作ってくれてます！
<img width="196" alt="スクリーンショット 2020-01-01 14 47 11" src="https://user-images.githubusercontent.com/50200649/71638526-a94f6480-2ca5-11ea-848b-0bd024225092.png">

**Comment by eatski** [comment]
お、まじか！
それなら/login作ってその画面表示させるでもいいかな

**Comment by eatski** [comment]
/update
もいるよね〜

**Comment by eatski** [comment]
削除はモーダル。、？
よくわからなくなってきた

**Comment by ymucm** [comment]
<img width="428" alt="スクリーンショット 2020-02-02 1 51 11" src="https://user-images.githubusercontent.com/50200649/73595661-8ba04400-455e-11ea-98df-38c308bac93a.png">
管理者画面の変更はモーダル？削除はわからんです、、

**Comment by kaorisugawara** [comment]
全然見てなくてすまんやけどまとめると

/ : 有給一覧画面
/new : 新規申請画面
/admin : 管理者画面（全ユーザー有給取得一覧画面）
/login : ログイン画面

モーダル・・？？
変更申請
削除申請

モーダルについて、

有給一覧画面は変更・削除ともにどっちでもいいけど、削除はモーダルのほうが楽かな。
サクッと消せる。でもcould。

管理者画面の場合は変更・削除申請どっちもモーダルのほうがユーザビリティはいいと思う。
ページにすると、遷移する分アクションが増えちゃうので。ただ使うのが嶋田さんだけっていうのもあるので気持ち的にはcoludくらい。
ページにした場合だけど、どこからきたのかによって出すページと戻るページが変わるのがめんどい（混乱するかも）。
一度ちゃんと話して図にまとめたいっすね

**Comment by kaorisugawara** [comment]
/admin?{userId} 管理者がユーザーの一覧画面を操作する
/admin/new?{userId} 管理者がユーザーの新規申請をする

**Comment by eatski** [comment]
- `/` : 有給一覧画面
  - モーダルで以下に遷移
    - 変更申請
    - 削除申請
- `/new` : 新規申請画面
- `/admin` : 管理者画面（全ユーザー有給取得一覧画面）
- `admin/{userId}` :  管理者がユーザーの一覧画面を操作する
- `/admin/new/{userId}` :  管理者がユーザーの新規申請をする
