### ISSUE TITLE
デプロイ先を決める

### ISSUE THREAD

**Issue by mosa-architect-study** [mosa-architect-study/replace-kintai#2]
google cloud platform / aws / azure / 2階にあるwindowsのPC（wasで動いてる）

**Comment by eatski** [comment]
https://mosa.slack.com/archives/CNQ12HXBL/p1570257393002100

**Comment by kaorisugawara** [comment]
一ヶ月の概算を出してもらう
mysql/オーロラ

**Comment by eatski** [comment]
heroku + firebase
