### ISSUE TITLE
Atoms作成

### ISSUE THREAD

**Issue by eatski** [mosa-architect-study/replace-kintai#27]
()に作業者名を入れてね

- [x] text (大久保)
- [x] caption (芳賀)
- [x] icon (菅原)
- [x] toggle (山内)
- [x] input-date (近江)
- [x] textarea (大久保)
- [x] button (山内)
- [x] user-icon (菅原)

**Comment by mosa-architect-study** [comment]
・text例
![スクリーンショット 2019-10-19 16 05 32](https://user-images.githubusercontent.com/52617593/67139353-565f3700-f28a-11e9-9a08-615ea70bbc75.png)
![スクリーンショット 2019-10-19 16 05 13](https://user-images.githubusercontent.com/52617593/67139349-4b0c0b80-f28a-11e9-91c7-d31e0a6e8158.png)
![スクリーンショット 2019-10-19 16 05 24](https://user-images.githubusercontent.com/52617593/67139351-519a8300-f28a-11e9-9026-cd94a31a8e05.png)

・caption例
![スクリーンショット 2019-10-19 16 06 25](https://user-images.githubusercontent.com/52617593/67139368-70007e80-f28a-11e9-9b85-742e57c652b1.png)
![スクリーンショット 2019-10-19 16 06 30](https://user-images.githubusercontent.com/52617593/67139369-742c9c00-f28a-11e9-9777-5606e887d8b8.png)

・icon例
![スクリーンショット 2019-10-19 16 07 17](https://user-images.githubusercontent.com/52617593/67139375-8f97a700-f28a-11e9-884f-e9e45905e39f.png)
![スクリーンショット 2019-10-19 16 07 27](https://user-images.githubusercontent.com/52617593/67139379-932b2e00-f28a-11e9-996c-d44af8ac0d4b.png)

・toggle例
下記の例は3つのボタンをつなげたもの（この状態はAtomsでは作らない）
![スクリーンショット 2019-10-19 16 08 27](https://user-images.githubusercontent.com/52617593/67139393-b524b080-f28a-11e9-90ef-8a1ffe0524c9.png)

・input-date例
![スクリーンショット 2019-10-19 16 09 09](https://user-images.githubusercontent.com/52617593/67139402-d1c0e880-f28a-11e9-9745-982f30b63551.png)

・textarea例
![スクリーンショット 2019-10-19 16 09 44](https://user-images.githubusercontent.com/52617593/67139410-e3a28b80-f28a-11e9-96f7-4ef126c4e65b.png)

・button例
![スクリーンショット 2019-10-19 16 10 11](https://user-images.githubusercontent.com/52617593/67139414-f321d480-f28a-11e9-9857-e03bfe5d0349.png)

・use-icon
![スクリーンショット 2019-10-19 16 10 39](https://user-images.githubusercontent.com/52617593/67139423-03d24a80-f28b-11e9-9990-95a29bee4ffa.png)

**Comment by eatski** [comment]
【注意】
stateはAtomsレベルのコンポーネントで持たないようにお願いいたします。
stateは親コンポーネントで管理するためです。
