### ISSUE TITLE
DB設計

### ISSUE THREAD

**Issue by kaorisugawara** [mosa-architect-study/replace-kintai#42]
データ移行もここでやる？

**Comment by eatski** [comment]
> データ移行もここでやる？

やりたい理由がありますか？

**Comment by eatski** [comment]
DB設計は基本現行そのままでいいと思ってますがどうでしょう。

**Comment by t-omi** [comment]
わたしは問題ないと思います！

**Comment by t-omi** [comment]
設計書作成途中

https://docs.google.com/spreadsheets/d/1oaUPToXvpuBVAUVXCNAzXJGa9x0MUJh7H0hir54kelA/edit#gid=0
