### ISSUE TITLE
AtomコンポーネントのPropsインターフェースをある程度決めたい

### ISSUE THREAD

**Issue by eatski** [mosa-architect-study/replace-kintai#45]
Atomsコンポーネントに渡すpropsのインターフェースを統一させたい。
https://github.com/mosa-architect-study/replace-kintai/pull/44 のような形で、"1","2","3"のような数値文字列を渡してそれをthemeで持ってる定数にマッピングさせる書き方で良いか？

sizeは何パターン持った方が良いか？

**Comment by eatski** [comment]
https://mosa.slack.com/archives/CNQ12HXBL/p1572362318005100

**Comment by kaorisugawara** [comment]
完了
