### ISSUE TITLE
猛者勤怠のロゴ作成

### ISSUE THREAD

**Issue by eatski** [mosa-architect-study/replace-kintai#95]
![image](https://user-images.githubusercontent.com/19850020/71539590-cd4b3700-2981-11ea-86d6-2a8ae210c6b5.png)
こんな感じ⬆︎

**Comment by mosa-architect-study** [comment]
![mosakin](https://user-images.githubusercontent.com/52617593/71553512-e6bcb380-2a53-11ea-9345-f2ec37fcbfc6.png)

**Comment by y-ookubo** [comment]
![mosakintaiシンプル](https://user-images.githubusercontent.com/53105523/71818746-24ad7d80-30cd-11ea-8fc4-1af751b99e9c.png)

**Comment by t-omi** [comment]
<img width="230" alt="スクリーンショット 2020-01-20 14 51 32" src="https://user-images.githubusercontent.com/53106448/72701962-73125000-3b94-11ea-85f6-a1b75d4af593.png">

**Comment by t-omi** [comment]
<img width="230" alt="スクリーンショット 2020-01-20 14 47 39" src="https://user-images.githubusercontent.com/53106448/72701979-80c7d580-3b94-11ea-9782-f8ee135c414d.png">

**Comment by eatski** [comment]
/* MOSA KINTAI */

position: absolute;
width: 300px;
height: 69px;

font-family: Electrolize;
font-style: normal;
font-weight: normal;
font-size: 64px;
line-height: 49px;
/* or 77% */
letter-spacing: 0.1em;

color: #FFFFFF;

![image](https://user-images.githubusercontent.com/19850020/78501144-5d74f580-7795-11ea-97b4-4b850c594351.png)

**Comment by kaorisugawara** [comment]
はがっちがつくってくれたlogoコンポーネントかわいいのでそれでfixでいいのではと思ってるマン

**Comment by eatski** [comment]
一旦DONEにするで
![image](https://user-images.githubusercontent.com/19850020/78698369-33f6ce00-793d-11ea-8a19-c4ee602915d4.png)
